# Generated by Django 3.2.3 on 2021-07-29 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0002_alter_signup_dob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='signup',
        ),
    ]
