# Generated by Django 3.2.3 on 2021-07-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0005_alter_signup_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='password',
        ),
        migrations.AlterField(
            model_name='login',
            name='Email',
            field=models.EmailField(max_length=250),
        ),
    ]
