# Generated by Django 3.2.3 on 2021-07-29 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faceapp', '0003_auto_20210729_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Mobile_Number', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=20)),
                ('DOB', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=20)),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceapp.signup')),
            ],
        ),
    ]
