# Generated by Django 3.2.3 on 2021-07-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0004_login_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Gender',
            field=models.CharField(max_length=10),
        ),
    ]
