# Generated by Django 3.2.3 on 2021-07-29 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0006_auto_20210729_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='faceapp.signup'),
        ),
    ]
