# Generated by Django 3.2.3 on 2021-07-31 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0007_login_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='signup',
        ),
    ]
